name: Build and Test

on:
  schedule:
    - cron: "0 2 * * 1" # Every Monday at 2 AM
  workflow_dispatch:

env:
  GO_VERSION: "1.22"
  NODE_VERSION: "18"

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            name: Linux
          - os: windows-latest
            platform: windows/amd64
            name: Windows
          - os: macos-latest
            platform: darwin/amd64
            name: macOS Intel
          - os: macos-latest
            platform: darwin/arm64
            name: macOS ARM

    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    name: Build ${{ matrix.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci --prefer-offline

      - name: Install Go dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./...

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Test build
        run: wails build --clean --platform ${{ matrix.platform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.name }}
          path: build/bin/
          retention-days: 7
