name: Auto-merge Dependabot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if PR is ready for auto-merge
        id: check-pr
        run: |
          # Get PR details
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_TITLE="${{ github.event.pull_request.title }}"

          echo "PR Number: $PR_NUMBER"
          echo "PR Title: $PR_TITLE"

          # Check if this is a minor/patch update
          if echo "$PR_TITLE" | grep -E "(deps\(go\)|deps\(npm\)).*: bump.*to.*\.(patch|minor)"; then
            echo "auto_merge=true" >> $GITHUB_OUTPUT
            echo "This is a minor/patch update - eligible for auto-merge"
          elif echo "$PR_TITLE" | grep -E "deps.*: bump.*from.*to"; then
            echo "auto_merge=false" >> $GITHUB_OUTPUT
            echo "This appears to be a major update - manual review required"
          else
            echo "auto_merge=false" >> $GITHUB_OUTPUT
            echo "Unknown update type - manual review required"
          fi

      - name: Wait for CI checks
        if: steps.check-pr.outputs.auto_merge == 'true'
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 1800 # 30 minutes

      - name: Auto-approve PR
        if: steps.check-pr.outputs.auto_merge == 'true' && steps.wait-for-ci.outputs.conclusion == 'success'
        run: |
          gh pr review --approve "${{ github.event.pull_request.number }}" --body "Auto-approved by GitHub Actions for dependency update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.check-pr.outputs.auto_merge == 'true' && steps.wait-for-ci.outputs.conclusion == 'success'
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major updates
        if: steps.check-pr.outputs.auto_merge == 'false'
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "🔍 This appears to be a major dependency update that requires manual review. Please check the changelog and test thoroughly before merging."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
